// Code generated by gen-handler-registry. DO NOT EDIT.

package main

import (
	"github.com/kmdeveloping/go-cqrs/cqrs"
	"github.com/kmdeveloping/go-cqrs/example/handlers"
)

func registerHandlers() {
	// Register handlers
	cqrs.RegisterCommandHandler(&handlers.DoThatCommandHandler{})
	cqrs.RegisterQueryHandler(&handlers.GetNameQueryHandler{})
	cqrs.RegisterEventHandler(&handlers.SomeEventHandler{})
	cqrs.RegisterEventHandler(&handlers.SomeOtherEventHandler{})
	cqrs.RegisterValidator(&handlers.DoSomethingCommandValidator{})
}
